export const staticData = {
  role: [
    {
      code: "MNG",
      name: "manager",
      isApproveApartment: true,
      isApproveUser: true,
      isApprove: true,
      isApproveComment: true,
      isManager: true,
      isCreateApartment: false,
      isEditApartment: true,
      isReport: false,
      isCreateOrEditComment: true,
    },
    {
      code: "O",
      name: "Owner",
      isApproveApartment: false,
      isApproveUser: false,
      isApprove: false,
      isApproveComment: true,
      isManager: false,
      isCreateApartment: true,
      isEditApartment: true,
      isReport: true,
      isCreateOrEditComment: true,
    },
    {
      code: "R",
      name: "renter",
      isApproveApartment: false,
      isApproveUser: false,
      isApprove: false,
      isApproveComment: false,
      isManager: false,
      isCreateApartment: false,
      isEditApartment: false,
      isReport: false,
      isCreateOrEditComment: true,
    },
    {
      code: "A",
      name: "admin",
      isApproveApartment: true,
      isApproveUser: true,
      isApprove: true,
      isApproveComment: true,
      isManager: true,
      isCreateApartment: false,
      isEditApartment: true,
      isReport: false,
      isCreateOrEditComment: true,
    },
  ],
  apartmentTypes: [
    { name: "Nhà trọ bình dân", code: "0001" },
    { name: "Chung cư mini", code: "0002" },
    { name: "Chung cư", code: "0003" },
    { name: "Nhà riêng", code: "0004" },
    { name: "Home Stay", code: "0005" },
  ],
  kitchenType: [
    {
      name: "Chung",
      code: "001",
    },
    {
      name: "Riêng",
      code: "002",
    },
    {
      name: "Không nấu ăn",
      code: "003",
    },
    {
      name: "Không có",
      code: "004",
    },
  ],
  toiletType: [
    {
      name: "Khép kín",
      code: "001",
    },
    {
      name: "Không khép kín",
      code: "002",
    },
    ,
    {
      name: "Không có",
      code: "003",
    },
  ],
  user: [
    {
      name: "Manager",
      personNo: "0000000",
      email: "nguyenthaitiep206@gmail.com",
      roleCode: "MNG",
      password: "123qwe",
    },
  ],
  postPrice: [
    { id: 1, name: "1 Tuần", time: 7, price: 100000, code: "1W" },
    { id: 2, name: "2 Tuần", time: 14, price: 195000, code: "2W" },
    { id: 3, name: "3 Tuần", time: 21, price: 270000, code: "3W" },
    { id: 4, name: "30 ngày", time: 30, price: 350000, code: "1T" },
    { id: 5, name: "60 ngày", time: 60, price: 600000, code: "2T" },
  ],
};
