export const staticData = {
  role: [
    {
      code: "MNG",
      name: "manager",
      isApproveApartment: true,
      isApproveUser: true,
      isApprove: true,
      isApproveComment: true,
      isManager: true,
      isCreateApartment: false,
      isEditApartment: true,
      isReport: false,
      isCreateOrEditComment: true,
    },
    {
      code: "O",
      name: "Owner",
      isApproveApartment: false,
      isApproveUser: false,
      isApprove: false,
      isApproveComment: true,
      isManager: false,
      isCreateApartment: true,
      isEditApartment: true,
      isReport: true,
      isCreateOrEditComment: true,
    },
    {
      code: "R",
      name: "renter",
      isApproveApartment: false,
      isApproveUser: false,
      isApprove: false,
      isApproveComment: false,
      isManager: false,
      isCreateApartment: false,
      isEditApartment: false,
      isReport: false,
      isCreateOrEditComment: true,
    },
    {
      code: "A",
      name: "admin",
      isApproveApartment: true,
      isApproveUser: true,
      isApprove: true,
      isApproveComment: true,
      isManager: true,
      isCreateApartment: false,
      isEditApartment: true,
      isReport: false,
      isCreateOrEditComment: true,
    },
  ],
  apartmentTypes: [
    { name: "Nhà trọ bình dân", code: "0001" },
    { name: "Chung cư mini", code: "0002" },
    { name: "Chung cư", code: "0003" },
    { name: "Nhà riêng", code: "0004" },
    { name: "Home Stay", code: "0005" },
  ],
  kitchenType: [
    {
      name: "Chung",
      code: "001",
    },
    {
      name: "Riêng",
      code: "002",
    },
    {
      name: "Không nấu ăn",
      code: "003",
    },
    {
      name: "Không có",
      code: "004",
    },
  ],
  toiletType: [
    {
      name: "Khép kín",
      code: "001",
    },
    {
      name: "Không khép kín",
      code: "002",
    },
    ,
    {
      name: "Không có",
      code: "003",
    },
  ],
};
